version: '3.3'
services:
    baserow:
        container_name: baserow
        environment:
            - 'BASEROW_PUBLIC_URL=https://l92.168.2.3:3021'
        volumes:
            - 'baserow_data:/baserow/data'
        ports:
            - '3021:80'
        restart: unless-stopped
        image: 'baserow/baserow:1.10.1'