version: "3.8"
services:
  dockge:
    image: louislam/dockge:latest
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 5010:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/joelu/Docker/Dockge/data:/app/data
      - /home/joelu/Docker/Dockge/stacks:/home/joelu/Docker/Dockge/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/home/joelu/Docker/Dockge/stacks