version: '2'
services:
  db:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /home/joelu/Docker/Kanboard/Configs/Kanboard2/kanboard_database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=UVxY26hNL4qmo
      - MYSQL_DATABASE=kanboard
      - MYSQL_USER=kanboardGrfx
      - MYSQL_PASSWORD=nCRsB622o@6
    restart: always
      
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - 88:80
    volumes:
      - /home/joelu/Docker/Kanboard/Configs/Kanboard2/kanboard_data:/var/www/app/data
      - /home/joelu/Docker/Kanboard/Configs/Kanboard2/kanboard_plugins:/var/www/app/plugins
      - /home/joelu/Docker/Kanboard/Configs/Kanboard2/kanboard_ssl:/etc/nginx/ssl
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=kanboardGrfx
      - DATABASE_PASSWORD=nCRsB622o@6
      - DATABASE_NAME=kanboard
    depends_on:
      - db
    links:
      - db:db
    restart: always