version: "3"
services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    container_name: lychee_db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=lychee
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=lychee
  lychee:
    image: ghcr.io/linuxserver/lychee:latest
    container_name: lychee
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_USERNAME=lychee
      - DB_PASSWORD=lychee
      - DB_DATABASE=lychee
      - DB_PORT=3306
      - APP_URL: 192.168.1.58
    volumes:
      - ./config:/config
      - ./photos:/pictures
    ports:
      - 8125:80
    restart: unless-stopped
    depends_on:
      - db
