version: '3.3'
services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    restart: always
    ports:
     - '8085:8080'
    volumes:
     - ./trainingData:/usr/share/tesseract-ocr/5/tessdata
     - ./extraConfigs:/configs
    environment:
     - DOCKER_ENABLE_SECURITY=false